#ifndef __INC_PYTHON_rootlib_MANAGER_H__
#define __INC_PYTHON_rootlib_MANAGER_H__
#define initrootlibManager initrootlib
/* rootlib module */
/* rootlib.isExist */
/* rootlib.moduleImport */
/* rootlib.getList */
/* this lib includes modules under this lines.
	colorInfo
	consoleModule
	constInfo
	debugInfo
	dragon_soul_refine_settings
	emotion
	exception
	game
	interfaceModule
	introCreate
	introEmpire
	introLoading
	introLogin
	introLogo
	introSelect
	localeInfo
	mouseModule
	musicInfo
	networkModule
	new_introcreate
	new_introselect
	playerSettingModule
	Prototype
	RootLibCythonizer
	serverCommandParser
	serverInfo
	stringCommander
	system
	test_affect
	ui
	uiacce
	uiAffectShower
	uiAttachMetin
	uiAttr67Add
	uiAutoban
	uibattlepass
	uibiyolog
	uiCandidate
	uichangename
	uiCharacter
	uicharacterdetails
	uiChat
	uiCommon
	uiCube
	uicuberenewal
	uiDragonSoul
	uidungeontimer
	uidungeontrack
	uiEquipmentDialog
	uieventcalendar
	uiEx
	uiExchange
	uifishinggame
	uiGameButton
	uiGameOption
	uigameoptionnew
	uigemshop
	uiGuild
	uiHelp
	uiInventory
	uiitemcombination
	uiMapNameShower
	uiMessenger
	uiMiniMap
	uimission
	uiMoveChannel
	uiofflineshop
	uiofflineshopbuilder
	uiOption
	uiParty
	uipetsystem
	uiPhaseCurtain
	uipickitem
	uiPickMoney
	uiPlayerGauge
	uiPointReset
	uiPrivateShopBuilder
	uiprivateshopsearch
	uiQuest
	uirank
	uiRefine
	uiRestart
	uireward
	uiSafebox
	uisashskin
	uiScriptLocale
	uiselectitem
	uiselectitemex
	uiSelectMusic
	uiShop
	uishoprender
	uiskillcolor
	uispecialinventory
	uiswitchbot
	uiSystem
	uiSystemOption
	uiTarget
	uiTaskBar
	uiTip
	uiToolTip
	uiUploadMark
	uiWarpShower
	uiWeb
	uiwheeloffortune
	uiWhisper
	uiwiki
	utils
	wikiui
*/
void initrootlibManager();
#endif
